version: '2'
services:
  eurekaserver:
     image:   citadel/tmx-eureka-service:v5
     ports:
       - "8761:8761"
  zipkin:
    image: citadel/tmx-zipkinsvr:v5
    ports:
      - "9411:9411"
    environment:
      SERVER_PORT: "9411"
  zuulserver:
    image: citadel/tmx-zuulsvr:v5
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      ZIPKIN_URI: "http://zipkin/"
      ZIPKIN_PORT: "9411"
      ZIPKIN_URL: "http://zipkin:9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"      
  addressservice:
      image: citadel/tmx-address-service:v5
      ports:
        - "8085:8085"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8085"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        ZIPKIN_URI: "http://zipkin/"
        ZIPKIN_PORT: "9411"
        ZIPKIN_URL: "http://zipkin:9411"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  pupilservice:
      image: citadel/tmx-pupil-service:v5
      ports:
        - "8086:8086"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8086"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT:   "8761"
        ZIPKIN_URI: "http://zipkin/"
        ZIPKIN_PORT: "9411"
        ZIPKIN_URL: "http://zipkin:9411"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs5.papertrailapp.com:33437
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock        